FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8000
ENTRYPOINT [ "uvicorn" ]
CMD ["app:app", "--host", "0.0.0.0", "--port", "8000"]
